### ISSUE TITLE
Operations on individual rows

### ISSUE THREAD

**Issue by ForsythsGambit** [dthul/pymatrix#6]
Sorry to be a necromancer,I just found this project and thought it was a good way to automate matrix expressions with python--is there any plans for individual row operations within a matrix?

A syntax something along the lines of, Matrix1.Row1.multiply(-8) or similair.

**Comment by dthul** [comment]
I almost forgot this existed 😄
I don't plan to work on this project anymore but feel free to fork it if it fits your needs.
You might be better off using numpy though!

**Comment by ForsythsGambit** [comment]
Figured as much :) , I might take a stab at forking it later at some point when I've got the time.
